spring:
  application:
    name: identify
  config:
    import: optional:file:./secret.properties
  datasource:
    url: jdbc:postgresql://${host:localhost}:${postgres.port:5432}/${postgres.username}
    username: ${postgres.username}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

host: ${host}
jwt:
  access-token:
    secret: ${access-token.secret}
    expire: ${access-token.expire}
  refresh-token:
    secret: ${refresh-token.secret}
    expire: ${refresh-token.expire}
google:
  client-id: ${google.clientid}
  secret: ${google.secret}
internal:
  api:
    key: ${internal.api.key}