spring:
  application:
    name: chatbot
  config:
    import: optional:file:./secret.properties
  datasource:
    url: jdbc:postgresql://${host}:${postgres.port}/${postgres.database}
    username: ${postgres.username}
    password: ${postgres.password}
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true  # Tự động tạo bảng vector_store
        index-type: HNSW         # Thuật toán tìm kiếm nhanh (Postgres 16 hỗ trợ rất tốt)
        dimensions: 768          # 768 cho Gemini, 1536 cho OpenAI

server:
  port: 8082

host: ${host}

internal_api_key: ${internal.api.key}

gemini_api_key: ${google.genai.api.key}
